### ISSUE TITLE
Accès en écriture sur le bucket

### ISSUE THREAD

**Issue by yannickcpnv** [CPNV-ES-BI/BI_JAVA_AWS#3]
@NicolasGlassey,

Nous n'avons pas les accès en écriture sur le bucket fourni.

**Comment by NicolasGlassey** [comment]
@yannickcpnv 

Bonjour Yannick,

Pourriez-vous me donner des captures d'écran de ce que vous tentez de faire, par exemple via le cli.

Faites bien attention d'utilisation le bucket ayant le bon nommage (mentionné dans le fichier de permission d'AWS):
https://cpnv1.sharepoint.com/sites/22_23_BI_SiT2a-BI_JAVA_GCP/_layouts/15/download.aspx?UniqueId=ea2018569af045eeaaca0ec0b3077e0e&e=kVbUWM

**Comment by yannickcpnv** [comment]
Bonjour @NicolasGlassey,


Voici la capture d'écran avec la commande (en bas de la capture) essayant de créer un objet `test-file.txt` (souligné en rouge) dans le bucket `bi.java.cld.education`.

Le code java correspondant est celui affiché dans la méthode `createObject`

![image](https://user-images.githubusercontent.com/78364651/208669027-14bd7456-0b62-43c0-8b5c-354f3447a799.png)

**Comment by NicolasGlassey** [comment]
@yannickcpnv 

Il y avait une erreur de "typo" dans les permissions aws. Le Json référencait très bien le bucket (sinon vous n'auriez pas pu le créer), par contre la règle vous donnant tous les droits au sein de ce bucket était mal orthographié.

Ceci a été corrigé à l'instant en validant cela via le CLI:

```
[Before fix]
λ aws s3 cp .\Downloads\ariane5.PNG s3://bi.java.cld.education --profile BI-JAVA-AWS
upload failed: Downloads\ariane5.PNG to s3://bi.java.cld.education/ariane5.PNG An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

[After fix]
C:\Users\nicolas.glassey
λ aws s3 cp .\Downloads\ariane5.PNG s3://bi.java.cld.education --profile BI-JAVA-AWS
upload: Downloads\ariane5.PNG to s3://bi.java.cld.education/ariane5.PNG
```

Pouvez-vous rester de votre côté ?

**Comment by yannickcpnv** [comment]
@NicolasGlassey

Ca fonctionne, je peux créer un objet et en supprimer un.
